---
abstract: 'RT Authentication using External Sources'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Authen-ExternalAuth
no_index:
  directory:
    - html
    - inc
    - xt
recommends:
  CGI::Cookie: 0
  DBI: 0
  Net::LDAP: 0
  Net::SSLeay: 0
requires:
  CGI::Cookie: 0
  DBI: 0
  Net::LDAP: 0
  Net::SSLeay: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-authen-externalauth
version: '0.26'
x_module_install_rtx_version: '0.38'
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
